version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000/api

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/solchain
      - JWT_SECRET=your_jwt_secret
      - BLOCKCHAIN_URL=http://blockchain:8545

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  blockchain:
    build:
      context: ./smart-contracts
      dockerfile: Dockerfile
    ports:
      - "8545:8545"

volumes:
  mongo_data: